# Golang CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  build:
    executor:
      name: go/default
      tag: "1.14"
    steps:
      - checkout
      - run: echo "deb https://dl.bintray.com/sobolevn/deb git-secret main" | sudo tee -a /etc/apt/sources.list
      - run: wget -qO - https://api.bintray.com/users/sobolevn/keys/gpg/public.key | sudo apt-key add -
      - run: sudo apt-get update && sudo apt-get install git-secret
      - run: echo $GPG_PRIVATE_KEY_V2 | tr ',' '\n' > ./private_key.gpg
      - run: gpg --batch --import ./private_key.gpg
      - run: git secret reveal -p $CIRCLECI_GPG_PASSWORD
      - go/load-cache
      - go/mod-download
      - go/save-cache
orbs:
  go: circleci/go@1.3.0
workflows:
  main:
    jobs:
      - build
