# Golang CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  build:
    executor:
      name: go/default
      tag: "1.14"
    steps:
      - checkout
      - git-secret/install_and_decrypt:
        working_directory: ~/
      - go/load-cache
      - go/mod-download
      - go/save-cache
orbs:
  go: circleci/go@1.3.0
  git-secret: lyvly/git-secret@0.1.0
workflows:
  main:
    jobs:
      - build
